### PR TITLE
Vagrantfile + Berkshelf + Spiceweasel

### PR DESCRIPTION
**Pull request by paulczar**
Created a Vagrantfile to create two scenarios  `chef` + `allinone` or `chef` + `single_compute` + `single_controller`.     Also uses `Berkshelf` to give an alternative to submodules and `Spiceweasel` to define the vagrant infrastructure.

### CODE REVIEW

**Comment by breu** [comment]
Hello @paulczar 

Was can you rebase this pull request again?  We do not accept pull requests that update the submodules as this is handled by our CI/Jenkins workflow.  

Thanks
@rackerjoe

**Comment by paulczar** [comment]
I'm still a bit of a git n00b.   What exactly do you need me to do?     maybe help me out with an example git rebase command ?

**Comment by hughsaunders** [comment]
Something like this: 

``` bash
git checkout master
git pull $remote master
git checkout vagrant
git rebase master
```

http://git-scm.com/book/en/Git-Branching-Rebasing

**Comment by paulczar** [comment]
Okay,  that did a bunch of stuff.   here's the commands I ran ..

```
git checkout master
git pull git@github.com:paulczar/chef-cookbooks.git master
git checkout vagrant
git rebase master
git push
```

here it complained that I was behind ... so ran a pull then the push.

```
git pull
git push
```

Let me know if that's got it into a useable state for you.

**Comment by hughsaunders** [comment]
Hi Paul, 
You will need to pull from rcbops/chef-cookbooks grizzly rather than your own branch, so that you get the correct submodule pointers. Also you don't need to pull after the rebase, but you will need to push -f as you are changing history on the remote (github).

**Comment by paulczar** [comment]
Thanks Hugh,   I based it off the Folsom branch so I was trying to keep it at the Folsom and push it back to the Folsom branch.   I would imagine I'll need to modify the Berksfile and a few other bits and pieces to work under master/grizzly

**Comment by hughsaunders** [comment]
Ah apologies, I should have checked which branch you were intending. But you still need to pull from upstream rather than your fork so you can get the current submodule pointers.

**Comment by paulczar** [comment]
I get errors when trying to do this..   Here's a gist of my full command line

https://gist.github.com/paulczar/5777035

and then if I try to do it starting with a git clone --recursive I get this -

https://gist.github.com/paulczar/5777094

**Comment by paulczar** [comment]
My changes aren't too dramatic ...  so if you could provide me with the workflow you'd prefer I use for the fork/clone/branch/submit/etc I can start from scratch and redo.   I have the feeling I must have done something screwy early on and this is never going to sync back in.

**Comment by hughsaunders** [comment]
Here is how I would go about cleaning this up...

``` bash
# Clean clone of rcbops
git clone --recursive -b folsom git@github.com:rcbops/chef-cookbooks.git; cd chef-cookbooks

# Fetch your commits
git fetch git@github.com:paulczar/chef-cookbooks.git vagrant

# Replay and squash the relevant commits onto the local vagrant branch:
git rebase --onto folsom c23a85b 4c8ca13 -i
```

This will open an editor, pick the first commit, squash the rest:

```
pick 1549687 vagrantfile and provisioning scripts$
squash ea80b37 berkshelf/spiceweasel working$
squash 5a1742f some work on chef-zero and more testing$
squash 0e94e24 tested two VM stack$
squash 71b128c cleaned up some doc$
squash 9152e67 cleaned up some doc$
squash 1bc1232 cleaned up some doc$
squash 4c8ca13 vagrantfile cleanup$
$
# Rebase c23a85b..4c8ca13 onto df0e07f$
#$
# Commands:$
#  p, pick = use commit$
#  r, reword = use commit, but edit the commit message$
#  e, edit = use commit, but stop for amending$
#  s, squash = use commit, but meld into previous commit$
#  f, fixup = like "squash", but discard this commit's log message$
#  x, exec = run command (the rest of the line) using shell$
#$
# If you remove a line here THAT COMMIT WILL BE LOST.$
# However, if you remove everything, the rebase will be aborted.$
#$
```

Again the editor will be opened, asking your to merge the commit messages into something sensible, do that. 

``` bash
# Create the vagrant branch pointing to the resulting commit
git checkout -b vagrant
```

The  vagrant branch should be one commit different from rcbops/folsom: 

``` bash
git log --stat
commit 5d5ab725a04a334b5e758ce26a9b935eef8cbdfd
Author: paulczar <paul@paulcz.net>
Date:   Mon Jun 10 10:12:10 2013 -0500

     * vagrantfile and provisioning scripts
     * berkshelf/spiceweasel
     * some work on chef-zero and more testing
     * Two VM vagrant configuration

 .gitignore                        |    2 +
 Berksfile                         |   55 +++++++
 Berksfile-vagrant                 |    8 +
 Berksfile.lock                    |   11 ++
 Gemfile                           |    5 +
 README.md                         |   49 ++++++-
 Vagrantfile                       |  299 +++++++++++++++++++++++++++++++++++++
 environments/example.json         |    2 +-
 environments/vagrant-basic.json   |   60 ++++++++
 extras/admin.pem                  |   27 ++++
 extras/chef-validator.pem         |   27 ++++
 extras/chef-zero.pem              |   27 ++++
 extras/chef-zero.sh               |    3 +
 extras/client-chef.rb             |    4 +
 extras/client-zero.rb             |    4 +
 extras/client.rb                  |    4 +
 extras/knife-zero.rb              |    9 +
 extras/knife.rb                   |    9 +
 infrastructure.yml                |   80 ++++++++++
 nodes/allinone_node.json          |   12 ++
 nodes/single_compute_node.json    |   12 ++
 nodes/single_controller_node.json |   12 ++
 22 files changed, 719 insertions(+), 2 deletions(-)

commit df0e07fa8b55110c6323c1659fc92b4acb14c411
Author: rcbjenkins <rcb-deploy@lists.rackspace.com>
Date:   Fri Jun 14 02:22:39 2013 -0500

    Auto Updating glance submodule

 cookbooks/glance |    2 +-
 1 files changed, 1 insertions(+), 1 deletions(-)
```

Now you can push to github, -f is required as the rebase has changed history.

**Comment by paulczar** [comment]
Okay awesome.   to clean up the mess here,  I'm going to close the PR and open a new one with the fresh push.

**Pull request closed without merging**
