### PR TITLE
bump mysql to latest upstream

### PR DESCRIPTION
**Pull request by brc**
currently broken; points to nonexistent commit.

### CODE REVIEW

**Comment by breu** [comment]
Are you sure this one works?  You might want to change it to the commit that v4.2.3rc is using.

**Comment by claco** [comment]
I'm betting most likely yes, since they fixed the same error we were getting:  https://tickets.opscode.com/browse/COOK-3752

**Comment by brc** [comment]
tested in my personal cluster last night, seemed to work fine.  but that didn't include exerstack tests etc

**Comment by brc** [comment]
Closing this PR.

```
commit b50e994540bffe502e7f69d8847776082153d2f4
Merge: 733f291 e9e9535
Author: Jason Cannavale <jason@cannavale.com>
Date:   Tue Oct 15 07:51:46 2013 -0700

    Merge pull request #613 from rackerjoe/master

    fix mysql cookbook submodule pointer to point to an older version that works
```

**Pull request closed without merging**
