### PR TITLE
[US449] Added support for testing with Vagrant+Berkshelf+Spiceweasel.

### PR DESCRIPTION
**Pull request by paulczar**
- vagrantfile and provisioning scripts
  - berkshelf/spiceweasel
  - some work on chef-zero and more testing
  - Two VM vagrant configuration

Created a Vagrantfile to create two scenarios  `chef` + `allinone` or `chef` + `single_compute` + `single_controller`.     Also uses `Berkshelf` to give an alternative to submodules and `Spiceweasel` to define the vagrant infrastructure.

### CODE REVIEW

**Comment by paulczar** [comment]
This is a replacement PR for https://github.com/rcbops/chef-cookbooks/pull/431.   which hopefully is now usable.

**Comment by claco** [comment]
@paulczar Thanks for sticking this out with us. This is awesome. I'll be reviewing it this afternoon and hopefully merging it.

**Comment by claco** [comment]
@paulczar I only have one thought/question:  The rcbops cookbooks references in Berkshelf are pointed to folsom, and if we ported this to the grizzly branch, we would also have to point the to the grizzly branch.

What if we instead always use the local version that's submoduled in?

cookbook 'nova', :path => './cookbooks/nova'

**Comment by paulczar** [comment]
The idea is to give an alternative to submodules,  they can be very painful to deal with,   especially when you're doing work in multiple branches etc.    The berkshelf stuff gives an independent way to manage and use the chef packages required.      The Community cookbooks @ stackforge are using berkshelf/spiceweasel for importing chef recipes rather than submodules,  would be good to converge with them at some point.

I'm working on porting this to the grizzly branch in the next couple of days and will do a PR for it.

**Comment by stephenlauck** [comment]
Adding branch/ref/tag information to the Berksfile also gives the added benefits of visibility into what branch of the cookbook is being used, can easily be updated and also is checked into version control.

**Pull request closed without merging**
