### PR TITLE
Fixing up role[ha-controller1]

### PR DESCRIPTION
**Pull request by galstrom21**
Reflecting changes in e7c6430483bb1655ed1511717c75d8cec5389c66

### CODE REVIEW

**Comment by breu** [comment]
Please submit a documentation update for this change

**Comment by jcannava** [comment]
please squash commits.

**Comment by galstrom21** [comment]
ABANDONED!!

**Comment by rpedde** [comment]
please re-open

**Comment by mancdaz** [comment]
galstrom21 is not an approved committer.  Please leave pull request open for a member of the engineering team to review.

**Pull request merged**
