### PR TITLE
 Added support for testing with Vagrant+Berkshelf+Spiceweasel.

### PR DESCRIPTION
**Pull request by paulczar**
- vagrantfile and provisioning scripts for grizzly branch
  - berkshelf/spiceweasel
  - Vagrantfile with chef server + several combinations of openstack scenarios.

### CODE REVIEW

**Comment by stephenlauck** [comment]
I checked what ref using branch 'grizzly' for glance pulled down and I don't think they are pinning branch to grizzly but only updating to most recent from master. I submitted a Berksfile that doesn't pin all the cookbooks to 'grizzly'. I'm not sure though that this is totally correct either but it would be nice to track the dependency cookbooks with a branch, tag or ref in the Berksfile for visibility over submodules.

**Comment by willkelly** [comment]
Hello!  We've been experimenting with berkshelf in the swift-lite family of cookbooks lately.  We're going to discuss making berkshelf part of our release process on Tuesday.  We don't want to pull in berkshelf without also committing to keeping everything updated.

I'll update this card with the results of that meeting to keep everything in the open.

For the time being, we're holding off on including berkshelf.

**Comment by jcannava** [comment]
@paulczar Our apologies for the lack of communication on this and https://github.com/rcbops/chef-cookbooks/pull/444. We continue to look at berkshelf for inclusion as we progress, however, at this time we have chosen not to proceed with its inclusion.

**Comment by willkelly** [comment]
We are using berkshelf on our new swift cookbooks: https://github.com/rcbops-cookbooks/swift-lite and https://github.com/rcbops-cookbooks/swift-private-cloud, so we are definitely listening to your feedback as we move forward, but we are not yet ready to retrofit our compute cookbooks.

**Pull request closed without merging**
